version: "3.8"

services:
  mongodb:
    container_name: ${COMPOSE_PROJECT_NAME}-mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${PROJECT_DATA_PATH:-${PWD}}/mongodb:/data/db:rw,Z